### ISSUE TITLE
Pesquisa de Eventos e Colaboradores

### ISSUE THREAD

**Issue by tassioauad** [GDGTresRios/DesafioGDG1Mobile#17]
Primeiro ponto é que o campo de busca tanto de eventos quanto de colaboradores está com uma borda anormal como mostra a imagem abaixo e isso deve ser corrigido.

![dd4](https://cloud.githubusercontent.com/assets/771016/15986651/38d453e0-2fe3-11e6-882d-82467d3d3bec.png)

Segundo pondo é que quando se busca um evento ou colaborador mas não é encontrado nada nessa busca, o aplicativo não exibe uma mensagem de feedback a respeito disso, apenas mostra a tela em branco. Isso deve ser melhorado com alguma mensagem.

**Comment by WanderleiSantos** [comment]
No nexus 4 não apareceu essa borda anormal, vou emular em outros modelos, e colocar a mensagem de feedback.

**Comment by tassioauad** [comment]
Seu Android é o 5 ou 6?

**Comment by WanderleiSantos** [comment]
5.0 no celular está de boa, quando coloco no emulador acontece a situação da linha anormal em ambos 5.0 e 6.0.

Corrigido!!!
