### ISSUE TITLE
Melhoria de Recursos no Perfil do Evento

### ISSUE THREAD

**Issue by tassioauad** [GDGTresRios/DesafioGDG1Mobile#18]
Perfil do evento está bem vazio e sem recurso também. Sugiro algumas melhorias:
- Possibilitar que o usuário acesse a busca por eventos de mesma categoria que o evento do perfil.
- Possibilitar que o usuário acesso o perfil do colaborador através do perfil do evento.

**Comment by tassioauad** [comment]
Trabalhando nisso...

**Comment by tassioauad** [comment]
Ok. Conclui essa issue e aproveitei pra algumas pequenas melhorias visuais, mesmo que não tenha a ver com essa issue.

Farei o pull request para esse repositório. Não vou fechar até que alguém mais avalie e confirme que está tudo OK.

![screenshot_20160611-233147](https://cloud.githubusercontent.com/assets/771016/15988590/10559ccc-302d-11e6-983a-562404ba024d.png)
![screenshot_20160611-233151](https://cloud.githubusercontent.com/assets/771016/15988591/105af262-302d-11e6-8b2e-e1863be841ed.png)

**Comment by WanderleiSantos** [comment]
Massa Tássio, gostei das alterações. Vou esperar pra sincronizar aqui e dar uma olhada como ficou no celular!!

**Comment by tassioauad** [comment]
Boa. Lembrando que o foco da issue é a funcionalidade. A melhoradinha visual foi porque não aguentei aquele visual horrível de antes =X.

**Comment by WanderleiSantos** [comment]
Quando visualizo mais sobre o palestrante a tela não rola totalmente corta parte da descrição conforme imagem abaixo, nesta parte "Fabiano Cantor......" 

![screenshot_20160614-111145](https://cloud.githubusercontent.com/assets/4758984/16046003/40b3efc2-3221-11e6-9911-d4965eeb1705.png)

**Comment by tassioauad** [comment]
Abre uma issue pra correção do visual dessa tela.
